name: corona_oyun
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4
  draggable_floating_button:
  dynamic_theme: ^1.0.1
  url_launcher: ^5.0.1
  simple_animations: ^1.3.11
  flare_flutter: ^2.0.3
  audioplayers: ^0.15.1
  font_awesome_flutter: ^8.8.1
  flutter_custom_clippers: ^1.1.0
  shared_preferences: ^0.5.4+3
  dashed_container: ^1.0.1
  flutter_spinkit: "^4.1.0"
  loading: ^1.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flame: ^0.19.0
  clip_shadow: ^0.2.1

  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.7

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner: ^1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family : ssExtraLight
      fonts:
        - asset : assets/fonts/SourceSansPro-ExtraLight.ttf
    - family: ssLight
      fonts:
        - asset: assets/fonts/SourceSansPro-Light.ttf
    - family: ssRegular
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - kaynaklar/animasyon/
    - kaynaklar/eller_resim/
    - assets/
    - assets/images/bg/
    - assets/images/
    - assets/audio/sfx/blup.ogg
    - assets/audio/sfx/drop.ogg
    - assets/audio/sfx/slurp.ogg
    - assets/audio/bgm/home.mp3
    - kaynaklar/kendim_resimler/
    - kaynaklar/sehrim_resimler/
    - kaynaklar/ulkem_resimler/
    - assets/audio/tissue.ogg



  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
